//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefevi.TextSource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RGlobal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RGlobal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sefevi.TextSource.RGlobal", typeof(RGlobal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haqqımızda.
        /// </summary>
        public static string RAbout {
            get {
                return ResourceManager.GetString("RAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloq.
        /// </summary>
        public static string RBlog {
            get {
                return ResourceManager.GetString("RBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlaqə.
        /// </summary>
        public static string RContact {
            get {
                return ResourceManager.GetString("RContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Ətraflı.
        /// </summary>
        public static string RLearnMore {
            get {
                return ResourceManager.GetString("RLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsullar.
        /// </summary>
        public static string RProduct {
            get {
                return ResourceManager.GetString("RProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xidmətlərimiz.
        /// </summary>
        public static string RServices {
            get {
                return ResourceManager.GetString("RServices", resourceCulture);
            }
        }
    }
}
